name: 'setup libressl'
inputs:
  version:
    # renovate: datasource=github-tags depName=libressl-portable/portable versioning=semver registryUrl=https://github.com
    default: 4.0.0
runs:
  using: "composite"
  steps:
    - name: 'setup'
      uses: ./.github/actions/setup-dependency-cached
      id: setup
      with:
        id: libressl
        version: ${{ inputs.version }}
        run: |
          curl -LOsSf --retry 6 --retry-connrefused --max-time 999 \
          https://github.com/libressl/portable/releases/download/v${{ inputs.version }}/libressl-${{ inputs.version }}.tar.gz
          tar -xzf libressl-${{ inputs.version }}.tar.gz
          cd libressl-${{ inputs.version }}
          ./configure --disable-dependency-tracking --prefix=$HOME/libressl
          make install
