name: 'setup wolfssl'
inputs:
  flavour:
    required: true
    type: choice
    options:
      - all
      - opensslextra
env:
  # renovate: datasource=github-tags depName=wolfSSL/wolfssl versioning=semver extractVersion=^v?(?<version>.+)-stable$ registryUrl=https://github.com
  version: 5.7.6
runs:
  using: "composite"
  steps:
    - name: 'parameters'
      id: parameters
      if: ${{ inputs.flavour == 'all' }}
      shell: bash
      run: |
        echo "flags=--disable-dependency-tracking --enable-tls13 --enable-harden --enable-all \
            --disable-benchmark --disable-crypttests --disable-examples --prefix=$HOME/wolfssl-all" >> $GITHUB_OUTPUT
    - name: 'parameters'
      id: parameters
      if: ${{ inputs.flavour == 'opensslextra' }}
      shell: bash
      run: |
        echo "flags=--disable-dependency-tracking --enable-tls13 --enable-harden --enable-ech --enable-opensslextra \
            --disable-benchmark --disable-crypttests --disable-examples --prefix=$HOME/wolfssl-opensslextra" >> $GITHUB_OUTPUT
    - name: 'setup'
      uses: ./.github/actions/setup-dependency-cached
      id: setup
      with:
        id: wolfssl-${{ inputs.flavour }}
        version: ${{ env.version }}
        run: |
          curl -LOsSf --retry 6 --retry-connrefused --max-time 999 \
            https://github.com/wolfSSL/wolfssl/archive/v${{ env.version }}-stable.tar.gz
          tar -xzf v${{ env.version }}-stable.tar.gz
          cd wolfssl-${{ env.version }}-stable
          ./autogen.sh
          ./configure ${{ steps.parameters.outputs.flags }}
          make install