name: 'setup bearssl'
inputs:
  version:
    # unhandled
    default: 0.6
runs:
  using: "composite"
  steps:
    - name: 'setup'
      uses: ./.github/actions/setup-dependency-cached
      id: setup
      with:
        id: bearssl
        version: ${{ inputs.version }}
        run: |
          curl -LOsSf --retry 6 --retry-connrefused --max-time 999 \
          https://bearssl.org/bearssl-${{ inputs.version }}.tar.gz
          tar -xzf bearssl-${{ inputs.version }}.tar.gz
          cd bearssl-${{ inputs.version }}
          make
          mkdir -p $HOME/bearssl/lib $HOME/bearssl/include
          cp inc/*.h $HOME/bearssl/include
          cp build/libbearssl.* $HOME/bearssl/lib
